kind: pipeline
name: "Push on dev"
name: docker

steps:

- name: "Verify & Build"
  image: node:16
  commands:
  - npm install
- name: "Build docker image"
  image: plugins/docker
  command:
    - docker build . -t "{DRONE_COMMIT:0:7 }"

trigger:
  branch:
    - dev
