kind: pipeline
name: "Push on dev"

steps:

- name: "Verify & Build"
  image: node:16
  commands:
  - npm install

- name: "Build docker image"
  image: plugins/docker
  environment:
    REGISTRY_USERNAME:
      from_secret: rergistry_username
    REGISTRY_PASSWORD:
      from_secret: registry_password

  commands:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
    - docker build . -t ${DRONE_COMMIT:0:7}

trigger:
  branch:
    - dev
