kind: pipeline
type: docker
name: "Push on dev"

steps:
- name: "Verify & Build"
  image: node:16
  commands:
  - yarn install
  - yarn build

- name: "Build docker image"
  image: plugins/docker
  settings:
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    repo: aipyth/hackademy-supabase-app
    tags: ${DRONE_COMMIT:0:7}

trigger:
  branch:
    exclude:
    - master
